//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranSmart.API.ErrMessages", typeof(ErrMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token.
        /// </summary>
        public static string Invalid_Access_Token {
            get {
                return ResourceManager.GetString("Invalid_Access_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string Invalid_User {
            get {
                return ResourceManager.GetString("Invalid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Or Invalid Refresh Token.
        /// </summary>
        public static string Invalid_User_Or_Invalid_Refresh_Token {
            get {
                return ResourceManager.GetString("Invalid_User_Or_Invalid_Refresh_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Declaration is locked.
        /// </summary>
        public static string IT_Declaration_Is_Locked {
            get {
                return ResourceManager.GetString("IT_Declaration_Is_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module and page are required!.
        /// </summary>
        public static string Module_And_Page_Are_Required {
            get {
                return ResourceManager.GetString("Module_And_Page_Are_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any one  page!.
        /// </summary>
        public static string Please_Select_Any_One_Page {
            get {
                return ResourceManager.GetString("Please_Select_Any_One_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[2-9]{1}[0-9]{3}[ -]?[0-9]{4}[ -]?[0-9]{4}$.
        /// </summary>
        public static string Regx_Aadhar {
            get {
                return ResourceManager.GetString("Regx_Aadhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^[0-9]{10}$.
        /// </summary>
        public static string Regx_Phone {
            get {
                return ResourceManager.GetString("Regx_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link expired.
        /// </summary>
        public static string Reset_Password_Link_Expired {
            get {
                return ResourceManager.GetString("Reset_Password_Link_Expired", resourceCulture);
            }
        }
    }
}
