//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a tool.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using TranSmart.Core.Result;
using TranSmart.Data;
using TranSmart.Data.Paging;
using TranSmart.Domain.Entities.Organization;
using TranSmart.Domain.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace TranSmart.Service.Organization
{
    public partial interface IEmployeeDeviceService : IBaseService<EmployeeDevice>
    {

    }

    public partial class EmployeeDeviceService : BaseService<EmployeeDevice>, IEmployeeDeviceService
    {
        public EmployeeDeviceService(IUnitOfWork uow) : base(uow)
        {

        }

        public override async Task<EmployeeDevice> GetById(Guid id)
        {
            return await UOW.GetRepositoryAsync<EmployeeDevice>().SingleAsync(
                predicate: x => x.ID == id,
                orderBy: o => o.OrderByDescending(x => x.AddedAt));
        }

        public override async Task<IPaginate<EmployeeDevice>> GetPaginate(BaseSearch baseSearch)
        {
            Domain.Models.Search.Organization.EmployeeDeviceSearch search = (Domain.Models.Search.Organization.EmployeeDeviceSearch)baseSearch;
            return await UOW.GetRepositoryAsync<EmployeeDevice>().GetPageListAsync(
                predicate: x => (string.IsNullOrEmpty(search.Name)
                     || x.MobileNumber.Contains(search.Name)
                     || x.HostName.Contains(search.Name))
                     && (!search.EmployeeId.HasValue || x.EmployeeId == search.EmployeeId)
                     && (!search.MobileNumber.HasValue || x.MobileNumber == search.MobileNumber)
                     && (!search.ComputerType.HasValue || x.ComputerType == search.ComputerType)
                     && (string.IsNullOrEmpty(search.HostName) || x.HostName.Contains(search.HostName)),
                index: search.Page, size: search.Size, sortBy: search.SortBy ?? "EmployeeId", ascending: !search.IsDescend);
        }
    }
}
