//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a tool.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TranSmart.Core;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TranSmart.Domain.Entities.Organization
{
    [Table("Org_EmployeeDevice")]
    public partial class EmployeeDevice : DataGroupEntity
    {
        [Required]
        public int EmployeeId { get; set; }
        [StringLength(1024)]
        public string MobileNumber { get; set; }
        [Required]
        public int ComputerType { get; set; }
        [StringLength(1024)]
        [Required]
        public string HostName { get; set; }
        public bool IsActZeroInstalled { get; set; }
        public bool IsKInstalled { get; set; }
        [Required]
        public DateTime InstalledOn { get; set; }
        public bool IsUninstalled { get; set; }
        public DateTime? UninstalledOn { get; set; }
    }
}
