//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a tool.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using TranSmart.Core;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TranSmart.Domain.Entities.Payroll
{
    public partial class DeductionComponent : DataGroupEntity
    {
        public Guid? EarningId { get; set; }
        public EarningComponent Earning { get; set; }
        public bool IsEditable { get; set; }
    }
}
