//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranSmart.Service.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Aadhaar number as of now exists..
        /// </summary>
        internal static string Aadhar_Already_Exists {
            get {
                return ResourceManager.GetString("Aadhar_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Aadhaar number should have 12 numbers..
        /// </summary>
        internal static string Aadhar_Must_Be_12_Numbers {
            get {
                return ResourceManager.GetString("Aadhar_Must_Be_12_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number is required..
        /// </summary>
        internal static string Account_No_Is_Required {
            get {
                return ResourceManager.GetString("Account_No_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number length should be the same as the bank account no of digits ({0})..
        /// </summary>
        internal static string Account_No_Required_Length {
            get {
                return ResourceManager.GetString("Account_No_Required_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number as of now exists..
        /// </summary>
        internal static string Account_Number_Already_Exists {
            get {
                return ResourceManager.GetString("Account_Number_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number should contain digit&apos;s only.
        /// </summary>
        internal static string AccountNo_Should_Contain_Digits_Only {
            get {
                return ResourceManager.GetString("AccountNo_Should_Contain_Digits_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The leave balance has already been adjusted for this leave type..
        /// </summary>
        internal static string ADJUST_LEAVE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("ADJUST_LEAVE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age should be greater than 15..
        /// </summary>
        internal static string Age_should_be_greater_than_15 {
            get {
                return ResourceManager.GetString("Age_should_be_greater_than_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already applied..
        /// </summary>
        internal static string Already_Applied {
            get {
                return ResourceManager.GetString("Already_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has already applied pre-consumable leaves for this leave type..
        /// </summary>
        internal static string Already_Applied_Pre_Consumable_Leaves {
            get {
                return ResourceManager.GetString("Already_Applied_Pre_Consumable_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already approved..
        /// </summary>
        internal static string Already_Approved {
            get {
                return ResourceManager.GetString("Already_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves applied for these dates..
        /// </summary>
        internal static string Already_Leves_Applied_For_this_Dates {
            get {
                return ResourceManager.GetString("Already_Leves_Applied_For_this_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves approved for these dates..
        /// </summary>
        internal static string Already_Leves_Approved_For_this_Dates {
            get {
                return ResourceManager.GetString("Already_Leves_Approved_For_this_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already record is exist for the same quarter type.
        /// </summary>
        internal static string Already_Record_Exist {
            get {
                return ResourceManager.GetString("Already_Record_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFH already applied for these dates.
        /// </summary>
        internal static string Already_WFH_Applied_For_this_Dates {
            get {
                return ResourceManager.GetString("Already_WFH_Applied_For_this_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-consumable leaves already applied..
        /// </summary>
        internal static string ALREDY_APPPLIED_PRECONSUMABLE_LEAVES {
            get {
                return ResourceManager.GetString("ALREDY_APPPLIED_PRECONSUMABLE_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied leaves are less than the minimum leaves..
        /// </summary>
        internal static string Applied_Leaves_are_less_Minimum_Leave {
            get {
                return ResourceManager.GetString("Applied_Leaves_are_less_Minimum_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied leaves are less than the minimum leaves..
        /// </summary>
        internal static string Applied_Leaves_Are_Less_Than_The_Minimum_Leaves {
            get {
                return ResourceManager.GetString("Applied_Leaves_Are_Less_Than_The_Minimum_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrear already exist..
        /// </summary>
        internal static string Arrear_Already_Exist {
            get {
                return ResourceManager.GetString("Arrear_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this days attendance already executed.
        /// </summary>
        internal static string Attendance_Already_Executed {
            get {
                return ResourceManager.GetString("Attendance_Already_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank is required!..
        /// </summary>
        internal static string Bank_Is_Required {
            get {
                return ResourceManager.GetString("Bank_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number and re-enter account number are not matching..
        /// </summary>
        internal static string Both_Account_Number_should_be_same {
            get {
                return ResourceManager.GetString("Both_Account_Number_should_be_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The break time must be greater than or equal to 0..
        /// </summary>
        internal static string BREAK_TIME_SHOULD_NOT_BE_NEGATIVE {
            get {
                return ResourceManager.GetString("BREAK_TIME_SHOULD_NOT_BE_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You can&apos;t apply WFH more than 6 days.
        /// </summary>
        internal static string Cannot_Apply_WFH_More_Than_Six_Days {
            get {
                return ResourceManager.GetString("Cannot_Apply_WFH_More_Than_Six_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reply can&apos;t be editable.
        /// </summary>
        internal static string Cannot_Be_Editable {
            get {
                return ResourceManager.GetString("Cannot_Be_Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Already You have applied client visit for these days.
        /// </summary>
        internal static string Client_Visit_Already_Applied {
            get {
                return ResourceManager.GetString("Client_Visit_Already_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client visit has been approved..
        /// </summary>
        internal static string Client_Visit_Already_Approved {
            get {
                return ResourceManager.GetString("Client_Visit_Already_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client visit has been rejected..
        /// </summary>
        internal static string Client_Visit_Already_Rejected {
            get {
                return ResourceManager.GetString("Client_Visit_Already_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you are applied client visits for these days.
        /// </summary>
        internal static string Client_Visit_Applied_For_These_Days {
            get {
                return ResourceManager.GetString("Client_Visit_Applied_For_These_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed ticket already exist..
        /// </summary>
        internal static string Closed_Ticket_Already_Exist {
            get {
                return ResourceManager.GetString("Closed_Ticket_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning component already exist..
        /// </summary>
        internal static string Component_Already_Exist {
            get {
                return ResourceManager.GetString("Component_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number must be number and 10 digits only.
        /// </summary>
        internal static string Contact_Number_Must_Be_Number_And_10_Digits_Only {
            get {
                return ResourceManager.GetString("Contact_Number_Must_Be_Number_And_10_Digits_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current department is similar to transfered department.
        /// </summary>
        internal static string Current_Dept_And_Tranfered_Dept_Are_Same {
            get {
                return ResourceManager.GetString("Current_Dept_And_Tranfered_Dept_Are_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist..
        /// </summary>
        internal static string Date_Is_Already_Exist {
            get {
                return ResourceManager.GetString("Date_Is_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth should be lesser than the current date..
        /// </summary>
        internal static string Date_Of_Birth_Should_Be_Less_Than_Current_Date {
            get {
                return ResourceManager.GetString("Date_Of_Birth_Should_Be_Less_Than_Current_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of joining should be greater than the date of birth..
        /// </summary>
        internal static string Date_Of_Joining_Should_Be_Greater_Than_Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date_Of_Joining_Should_Be_Greater_Than_Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of resignation should be greater than the date of joining..
        /// </summary>
        internal static string Date_Of_Resignation_Should_Be_Greater_Than_Date_Of_Joining {
            get {
                return ResourceManager.GetString("Date_Of_Resignation_Should_Be_Greater_Than_Date_Of_Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The declaration has been submitted..
        /// </summary>
        internal static string Declaration_Already_Submitted {
            get {
                return ResourceManager.GetString("Declaration_Already_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction component already exist..
        /// </summary>
        internal static string Deduction_Component_Already_Exist {
            get {
                return ResourceManager.GetString("Deduction_Component_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Pay Off Leave Type already exists.
        /// </summary>
        internal static string Default_Pay_Off_LeaveType_already_exists {
            get {
                return ResourceManager.GetString("Default_Pay_Off_LeaveType_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department already exists in the Paper.
        /// </summary>
        internal static string Department_Already_Exists_In_The_Paper {
            get {
                return ResourceManager.GetString("Department_Already_Exists_In_The_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department already removed from the Paper.
        /// </summary>
        internal static string Department_Already_Removed_From_The_Paper {
            get {
                return ResourceManager.GetString("Department_Already_Removed_From_The_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As same department selected in exceptions, please change the department..
        /// </summary>
        internal static string Department_There_In_Exception {
            get {
                return ResourceManager.GetString("Department_There_In_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation already exists in the Paper.
        /// </summary>
        internal static string Designation_Already_Exists_In_The_Paper {
            get {
                return ResourceManager.GetString("Designation_Already_Exists_In_The_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation not exist in the Paper.
        /// </summary>
        internal static string Designation_Not_Exist_in_the_Paper {
            get {
                return ResourceManager.GetString("Designation_Not_Exist_in_the_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As same designation selected in exceptions, please change the designation..
        /// </summary>
        internal static string Designation_There_In_Exception {
            get {
                return ResourceManager.GetString("Designation_There_In_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee department and leave type department are not matching..
        /// </summary>
        internal static string Different_Department {
            get {
                return ResourceManager.GetString("Different_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee designation and leave type designation are not matching..
        /// </summary>
        internal static string Different_Designation {
            get {
                return ResourceManager.GetString("Different_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves are not applicable for gender other than..
        /// </summary>
        internal static string Different_Gender {
            get {
                return ResourceManager.GetString("Different_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee location and leave type location are not matching..
        /// </summary>
        internal static string Different_Location {
            get {
                return ResourceManager.GetString("Different_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves are not applicable for a marital status other than..
        /// </summary>
        internal static string Different_Martial_Status {
            get {
                return ResourceManager.GetString("Different_Martial_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you don&apos;t have permission to close this ticket.
        /// </summary>
        internal static string Does_Not_Have_Permission_To_Close {
            get {
                return ResourceManager.GetString("Does_Not_Have_Permission_To_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you don&apos;t have permission to edit the response.
        /// </summary>
        internal static string Does_Not_Have_Permission_To_Edit {
            get {
                return ResourceManager.GetString("Does_Not_Have_Permission_To_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you don&apos;t have permission to assign this ticket.
        /// </summary>
        internal static string Does_Not_Have_Permission_To_Re_Assign {
            get {
                return ResourceManager.GetString("Does_Not_Have_Permission_To_Re_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you don&apos;t have access to post reply for this ticket.
        /// </summary>
        internal static string Does_Not_Have_Permission_To_Replay {
            get {
                return ResourceManager.GetString("Does_Not_Have_Permission_To_Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you don&apos;t have perssion to transfer this ticket.
        /// </summary>
        internal static string Does_Not_Have_Permission_To_Transfer {
            get {
                return ResourceManager.GetString("Does_Not_Have_Permission_To_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate user..
        /// </summary>
        internal static string Duplicate_User {
            get {
                return ResourceManager.GetString("Duplicate_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        internal static string Email_Already_Exist {
            get {
                return ResourceManager.GetString("Email_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee already exists..
        /// </summary>
        internal static string Employee_Already_Exists {
            get {
                return ResourceManager.GetString("Employee_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee bonus already exist..
        /// </summary>
        internal static string Employee_Bonus_Already_Exist {
            get {
                return ResourceManager.GetString("Employee_Bonus_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee payment information has been added..
        /// </summary>
        internal static string Employee_Payment_Information_Is_Already_Added_ {
            get {
                return ResourceManager.GetString("Employee_Payment_Information_Is_Already_Added.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee salary is already available..
        /// </summary>
        internal static string Employee_Salary_Already_Available {
            get {
                return ResourceManager.GetString("Employee_Salary_Already_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Un-Authorized with same date is already exists.
        /// </summary>
        internal static string Employee_UnAuthorized_With_Same_Date_is_already_exists {
            get {
                return ResourceManager.GetString("Employee_UnAuthorized_With_Same_Date_is_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t able to add, because the employee department is in the exception department..
        /// </summary>
        internal static string Exception_Department {
            get {
                return ResourceManager.GetString("Exception_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t able to add, because the employee designation is in exception designation..
        /// </summary>
        internal static string Exception_Designation {
            get {
                return ResourceManager.GetString("Exception_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t able to add, because the employee location is in the exception location..
        /// </summary>
        internal static string Exception_Location {
            get {
                return ResourceManager.GetString("Exception_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial from year is not editable..
        /// </summary>
        internal static string Financial_From_Year_Is_Not_Editable {
            get {
                return ResourceManager.GetString("Financial_From_Year_Is_Not_Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Oneday WFH , either First half or Second Half Should select.
        /// </summary>
        internal static string FirstHalf_Or_SecondHalf_Should_Select {
            get {
                return ResourceManager.GetString("FirstHalf_Or_SecondHalf_Should_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For one day leave , only either first half or second half should select.
        /// </summary>
        internal static string For_OneDay_Leave_Both_Halfs_Should_Not_Select {
            get {
                return ResourceManager.GetString("For_OneDay_Leave_Both_Halfs_Should_Not_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date is always greater than or equal to today&apos;s date..
        /// </summary>
        internal static string From_Date_AlwaysGreater_than_or_Equal_to_Today_Date {
            get {
                return ResourceManager.GetString("From_Date_AlwaysGreater_than_or_Equal_to_Today_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date is always greater than or equal to today&apos;s date..
        /// </summary>
        internal static string From_Date_Is_Always_Greater_Than_Today_Date {
            get {
                return ResourceManager.GetString("From_Date_Is_Always_Greater_Than_Today_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date should be less than the to date..
        /// </summary>
        internal static string From_Date_Should_be_less_then_The_To_Date {
            get {
                return ResourceManager.GetString("From_Date_Should_be_less_then_The_To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group employee&apos;s are not allowed as manager.
        /// </summary>
        internal static string Group_Emp_Not_Allowed_As_Manager {
            get {
                return ResourceManager.GetString("Group_Emp_Not_Allowed_As_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rental from and rental to date in house rent details..
        /// </summary>
        internal static string HRA_Invalid_From__And_To_Dates {
            get {
                return ResourceManager.GetString("HRA_Invalid_From _And_To_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentives and PayCut already exist..
        /// </summary>
        internal static string Incentives_And_PayCut_Already_Exist {
            get {
                return ResourceManager.GetString("Incentives_And_PayCut_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income tax limit is already exist..
        /// </summary>
        internal static string Income_Tax_Limit_Is_Already_exist {
            get {
                return ResourceManager.GetString("Income_Tax_Limit_Is_Already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income to is always greater than income from..
        /// </summary>
        internal static string IncomeTo_Greater_Than_IncomeFrom {
            get {
                return ResourceManager.GetString("IncomeTo_Greater_Than_IncomeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed on is required!.
        /// </summary>
        internal static string Installed_On_Is_Required {
            get {
                return ResourceManager.GetString("Installed_On_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid..
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arrear..
        /// </summary>
        internal static string Invalid_Arrear {
            get {
                return ResourceManager.GetString("Invalid_Arrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid declaration..
        /// </summary>
        internal static string Invalid_Declaration {
            get {
                return ResourceManager.GetString("Invalid_Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        internal static string Invalid_Email_Format {
            get {
                return ResourceManager.GetString("Invalid_Email_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid emergency contact number..
        /// </summary>
        internal static string Invalid_EmergencyContNo {
            get {
                return ResourceManager.GetString("Invalid_EmergencyContNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid employee..
        /// </summary>
        internal static string Invalid_Employee {
            get {
                return ResourceManager.GetString("Invalid_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid employee details..
        /// </summary>
        internal static string Invalid_Employee_Details {
            get {
                return ResourceManager.GetString("Invalid_Employee_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format..
        /// </summary>
        internal static string Invalid_Format {
            get {
                return ResourceManager.GetString("Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IFSC code.
        /// </summary>
        internal static string Invalid_IFSC_Code {
            get {
                return ResourceManager.GetString("Invalid_IFSC_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input format..
        /// </summary>
        internal static string Invalid_Input_Format {
            get {
                return ResourceManager.GetString("Invalid_Input_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid item..
        /// </summary>
        internal static string Invalid_Item {
            get {
                return ResourceManager.GetString("Invalid_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LateComer.
        /// </summary>
        internal static string Invalid_LateComers {
            get {
                return ResourceManager.GetString("Invalid_LateComers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid log response.
        /// </summary>
        internal static string Invalid_Log_Response {
            get {
                return ResourceManager.GetString("Invalid_Log_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        internal static string Invalid_Old_Password {
            get {
                return ResourceManager.GetString("Invalid_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PAN number format..
        /// </summary>
        internal static string Invalid_PAN_Format {
            get {
                return ResourceManager.GetString("Invalid_PAN_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Invalid PayMonth.
        /// </summary>
        internal static string Invalid_PayMonth {
            get {
                return ResourceManager.GetString("Invalid_PayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pay sheet..
        /// </summary>
        internal static string Invalid_PaySheet {
            get {
                return ResourceManager.GetString("Invalid_PaySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question is Invalid.
        /// </summary>
        internal static string Invalid_Question {
            get {
                return ResourceManager.GetString("Invalid_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TAN number format..
        /// </summary>
        internal static string Invalid_TAN_Format {
            get {
                return ResourceManager.GetString("Invalid_TAN_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ticket..
        /// </summary>
        internal static string Invalid_Ticket {
            get {
                return ResourceManager.GetString("Invalid_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string Invalid_User {
            get {
                return ResourceManager.GetString("Invalid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or refresh token.
        /// </summary>
        internal static string Invalid_User_Or_Refresh_Token {
            get {
                return ResourceManager.GetString("Invalid_User_Or_Refresh_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT declaration is locked..
        /// </summary>
        internal static string IT_DECLARTION_IS_LOCKED {
            get {
                return ResourceManager.GetString("IT_DECLARTION_IS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latecomer already exist..
        /// </summary>
        internal static string Latecomer_Already_Exist {
            get {
                return ResourceManager.GetString("Latecomer_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already exists..
        /// </summary>
        internal static string Lead_ContactNo_Is_Already_Exist {
            get {
                return ResourceManager.GetString("Lead_ContactNo_Is_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number should contain digits between 0 to 9..
        /// </summary>
        internal static string Lead_ContactNo_Is_Digits_Only {
            get {
                return ResourceManager.GetString("Lead_ContactNo_Is_Digits_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number should contain only 10 digits..
        /// </summary>
        internal static string Lead_ContactNo_Is_Equal_To_10_Digits_Only {
            get {
                return ResourceManager.GetString("Lead_ContactNo_Is_Equal_To_10_Digits_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This leave has already been approved..
        /// </summary>
        internal static string Leave_Already_Approved {
            get {
                return ResourceManager.GetString("Leave_Already_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave already cancelled.
        /// </summary>
        internal static string LEAVE_ALREADY_CANCELLED {
            get {
                return ResourceManager.GetString("LEAVE_ALREADY_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This leave has been rejected..
        /// </summary>
        internal static string Leave_Already_Rejected {
            get {
                return ResourceManager.GetString("Leave_Already_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Leave is already applied for this day(s).
        /// </summary>
        internal static string Leave_Applied_For_This_Day_s_ {
            get {
                return ResourceManager.GetString("Leave_Applied_For_This_Day(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!  your applied leave is approved for these days.
        /// </summary>
        internal static string Leave_Approved_For_This_Days {
            get {
                return ResourceManager.GetString("Leave_Approved_For_This_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The selected leave type doesn&apos;t accept half-day leaves..
        /// </summary>
        internal static string LEAVE_TYPE_NOT_ACCEPT_HALF_DAY_LEAVES {
            get {
                return ResourceManager.GetString("LEAVE_TYPE_NOT_ACCEPT_HALF_DAY_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves have been exceeded to maximum leaves..
        /// </summary>
        internal static string Leaves_are_Exceed_The_Maximum_Leaves {
            get {
                return ResourceManager.GetString("Leaves_are_Exceed_The_Maximum_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No leaves are available to apply..
        /// </summary>
        internal static string Leaves_Are_Not_Available_To_Apply {
            get {
                return ResourceManager.GetString("Leaves_Are_Not_Available_To_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Leaves are not available to approve.
        /// </summary>
        internal static string Leaves_are_Not_available_to_approve {
            get {
                return ResourceManager.GetString("Leaves_are_Not_available_to_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves exceeded the available leaves..
        /// </summary>
        internal static string Leaves_Exceed_Available_Leaves {
            get {
                return ResourceManager.GetString("Leaves_Exceed_Available_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves exceeded to the future day(s)..
        /// </summary>
        internal static string Leaves_Exceed_Future_Days {
            get {
                return ResourceManager.GetString("Leaves_Exceed_Future_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves are exceeded to the maximum leaves..
        /// </summary>
        internal static string Leaves_Exceed_Maximum_Leaves {
            get {
                return ResourceManager.GetString("Leaves_Exceed_Maximum_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves exceeded the past day(s)..
        /// </summary>
        internal static string Leaves_Exceed_Past_Days {
            get {
                return ResourceManager.GetString("Leaves_Exceed_Past_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves exceeded the available leaves..
        /// </summary>
        internal static string Leaves_Exceed_The_Available_Leaves {
            get {
                return ResourceManager.GetString("Leaves_Exceed_The_Available_Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves exceeded the future day(s)..
        /// </summary>
        internal static string Leaves_Exceed_The_Future_Day_s_ {
            get {
                return ResourceManager.GetString("Leaves_Exceed_The_Future_Day_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves exceeded the past day(s)..
        /// </summary>
        internal static string Leaves_Exceed_The_Past_Day_s_ {
            get {
                return ResourceManager.GetString("Leaves_Exceed_The_Past_Day_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves Exceeded Leave Applications.
        /// </summary>
        internal static string LEAVES_EXCEEDED_LEAVE_APPLICATIONS {
            get {
                return ResourceManager.GetString("LEAVES_EXCEEDED_LEAVE_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No leaves are available to apply..
        /// </summary>
        internal static string Leaves_Not_Avaible_To_Apply {
            get {
                return ResourceManager.GetString("Leaves_Not_Avaible_To_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loan deduction date should be greater than or equal to the loan release date..
        /// </summary>
        internal static string Loan_deducation_date_should_be_greaterthan_or_equal_to_the_loan_release_date {
            get {
                return ResourceManager.GetString("Loan_deducation_date_should_be_greaterthan_or_equal_to_the_loan_release_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same location has been selected in exceptions, please change the location..
        /// </summary>
        internal static string Location_There_In_Exception {
            get {
                return ResourceManager.GetString("Location_There_In_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login user does&apos;t belongs to any team.
        /// </summary>
        internal static string Login_User_Does_Not_Belongs_To_Any_Team {
            get {
                return ResourceManager.GetString("Login_User_Does_Not_Belongs_To_Any_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage anniversary should be greater than the date of birth..
        /// </summary>
        internal static string Marriage_Anniversery_Should_Be_Greater_Than_Date_Of_Birth {
            get {
                return ResourceManager.GetString("Marriage_Anniversery_Should_Be_Greater_Than_Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum leaves should be greater than or equal to minimum leaves..
        /// </summary>
        internal static string MAX_LEAVES_GREATER_THEN_OR_EQUAL_TO_MIN_LEAVES {
            get {
                return ResourceManager.GetString("MAX_LEAVES_GREATER_THEN_OR_EQUAL_TO_MIN_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly amount should be less than the loan amount..
        /// </summary>
        internal static string Monthly_Amount_Should_Be_Less_Than_Loan_Amount {
            get {
                return ResourceManager.GetString("Monthly_Amount_Should_Be_Less_Than_Loan_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee monthly salary should be more then zero..
        /// </summary>
        internal static string Monthly_Salary_Should_Be_MoreThen_Zero {
            get {
                return ResourceManager.GetString("Monthly_Salary_Should_Be_MoreThen_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name as of now exists..
        /// </summary>
        internal static string Name_already_exists {
            get {
                return ResourceManager.GetString("Name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not be the same..
        /// </summary>
        internal static string Name_Should_Not_Be_Same {
            get {
                return ResourceManager.GetString("Name_Should_Not_Be_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new balance should not be negative..
        /// </summary>
        internal static string NEW_BALANCE_SHOULD_NOT_BE_NEGATIVE {
            get {
                return ResourceManager.GetString("NEW_BALANCE_SHOULD_NOT_BE_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password cannot be same as your last five passwords. Please choose a different password..
        /// </summary>
        internal static string New_Password_Should_Be_Different_From_Old_Password {
            get {
                return ResourceManager.GetString("New_Password_Should_Be_Different_From_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questions found.
        /// </summary>
        internal static string No_Questions_Found {
            get {
                return ResourceManager.GetString("No_Questions_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found.
        /// </summary>
        internal static string No_Result_Found {
            get {
                return ResourceManager.GetString("No_Result_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ticket is closed..
        /// </summary>
        internal static string Not_Possible_To_Transfer {
            get {
                return ResourceManager.GetString("Not_Possible_To_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number already exists..
        /// </summary>
        internal static string Number_Already_Exists {
            get {
                return ResourceManager.GetString("Number_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one record can be accepted for settings..
        /// </summary>
        internal static string Only_One_Record_Is_Accepted {
            get {
                return ResourceManager.GetString("Only_One_Record_Is_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pan number already exists..
        /// </summary>
        internal static string Pan_Number_Already_Exists {
            get {
                return ResourceManager.GetString("Pan_Number_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once paper moved to live, changes can&apos;t be done.
        /// </summary>
        internal static string Paper_is_in_live {
            get {
                return ResourceManager.GetString("Paper_is_in_live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper name already exist.
        /// </summary>
        internal static string Paper_Name_Already_Exist {
            get {
                return ResourceManager.GetString("Paper_Name_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper not exist.
        /// </summary>
        internal static string Paper_Not_Exist {
            get {
                return ResourceManager.GetString("Paper_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add questions.
        /// </summary>
        internal static string Please_Add_Questions {
            get {
                return ResourceManager.GetString("Please_Add_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the administrator..
        /// </summary>
        internal static string Please_Contact_Administrator {
            get {
                return ResourceManager.GetString("Please_Contact_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable the status to move test to live.
        /// </summary>
        internal static string Please_Enable_Status_To_Move_Test_To_Live {
            get {
                return ResourceManager.GetString("Please_Enable_Status_To_Move_Test_To_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give the allocation emp screen..
        /// </summary>
        internal static string Please_Give_Allocation_Emp_Screen {
            get {
                return ResourceManager.GetString("Please_Give_Allocation_Emp_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your response .
        /// </summary>
        internal static string Please_Give_Valid_Response {
            get {
                return ResourceManager.GetString("Please_Give_Valid_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already exists.
        /// </summary>
        internal static string Question_Already_Exists {
            get {
                return ResourceManager.GetString("Question_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-9]$.
        /// </summary>
        internal static string Reg_Account_No {
            get {
                return ResourceManager.GetString("Reg_Account_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^[0-9]{10}$.
        /// </summary>
        internal static string Reg_Phone {
            get {
                return ResourceManager.GetString("Reg_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[2-9]{1}[0-9]{3}[ -]?[0-9]{4}[ -]?[0-9]{4}$.
        /// </summary>
        internal static string Regx_Aadhar {
            get {
                return ResourceManager.GetString("Regx_Aadhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \A(?:[a-z0-9!#$%&amp;amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;amp;&apos;*+/=?^_`{|}~-]+)*@(?:\A(?:[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z.
        /// </summary>
        internal static string Regx_Email {
            get {
                return ResourceManager.GetString("Regx_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$.
        /// </summary>
        internal static string Regx_Email_Validation {
            get {
                return ResourceManager.GetString("Regx_Email_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Z]{4}0[A-Z0-9]{6}$.
        /// </summary>
        internal static string Regx_IFSC_Code {
            get {
                return ResourceManager.GetString("Regx_IFSC_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[0-9]{10}$.
        /// </summary>
        internal static string Regx_Mobile_Number {
            get {
                return ResourceManager.GetString("Regx_Mobile_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?i)[A-Z]{3}[ABCFGHLJPTF]{1}[A-Z]{1}[0-9]{4}[A-Z]{1}$.
        /// </summary>
        internal static string Regx_Pan {
            get {
                return ResourceManager.GetString("Regx_Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A-Z]{1}[0-9]{7}.
        /// </summary>
        internal static string Regx_Passport {
            get {
                return ResourceManager.GetString("Regx_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([aA-zZ]){4}([0-9]){5}([aA-zZ]){1}$.
        /// </summary>
        internal static string Regx_Tan {
            get {
                return ResourceManager.GetString("Regx_Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date must be greater than or equal to the employee joining date..
        /// </summary>
        internal static string Release_date_must_be_greater_than_or_equal_to_the_employee_joining_date {
            get {
                return ResourceManager.GetString("Release_date_must_be_greater_than_or_equal_to_the_employee_joining_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resignation approval should be greater than or equal to resigned..
        /// </summary>
        internal static string Resignation_Approval_Is_Greater_Than_Are_Equal_To_Resigned {
            get {
                return ResourceManager.GetString("Resignation_Approval_Is_Greater_Than_Are_Equal_To_Resigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected leave type already exist for this employee.
        /// </summary>
        internal static string Selected_LeaveType_Alredy_Exist {
            get {
                return ResourceManager.GetString("Selected_LeaveType_Alredy_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers are not allowed under groups.
        /// </summary>
        internal static string Selected_User_Is_Manager {
            get {
                return ResourceManager.GetString("Selected_User_Is_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for this origination have been added..
        /// </summary>
        internal static string Settings_For_This_Origination_Already_Added_ {
            get {
                return ResourceManager.GetString("Settings_For_This_Origination_Already_Added.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This slab already exists..
        /// </summary>
        internal static string Slab_Already_Exists {
            get {
                return ResourceManager.GetString("Slab_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Something went wrong.
        /// </summary>
        internal static string Something_Went_Wrong {
            get {
                return ResourceManager.GetString("Something_Went_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You cannot update the loan once the recovery has started..
        /// </summary>
        internal static string Sorry____You_Can_Not_Update_The_Loan_Once_Recovery_Is_Started {
            get {
                return ResourceManager.GetString("Sorry!!,_You_Can_Not_Update_The_Loan_Once_Recovery_Is_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! you don&apos;t have access.
        /// </summary>
        internal static string Sorry_You_Does_Not_Have_Access {
            get {
                return ResourceManager.GetString("Sorry_You_Does_Not_Have_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This state name as of now exists..
        /// </summary>
        internal static string State_Name_already_exists {
            get {
                return ResourceManager.GetString("State_Name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required..
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan number already exists..
        /// </summary>
        internal static string Tan_Number_Already_Exists {
            get {
                return ResourceManager.GetString("Tan_Number_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The financial year has been added..
        /// </summary>
        internal static string The_Financial_Year_Already_Added_ {
            get {
                return ResourceManager.GetString("The_Financial_Year_Already_Added.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The financial year should have only 12 months..
        /// </summary>
        internal static string The_Financial_Year_Should_Have_Only_12_Months_ {
            get {
                return ResourceManager.GetString("The_Financial_Year_Should_Have_Only_12_Months.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous financial year is still in the process..
        /// </summary>
        internal static string The_Previous_Financial_Year_Still_In_Process_ {
            get {
                return ResourceManager.GetString("The_Previous_Financial_Year_Still_In_Process.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected financial year is closed..
        /// </summary>
        internal static string The_selected_financial_year_is_closed {
            get {
                return ResourceManager.GetString("The_selected_financial_year_is_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no replication data .
        /// </summary>
        internal static string There_Is_No_Replication_Data {
            get {
                return ResourceManager.GetString("There_Is_No_Replication_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket is closed so, not possbile to do changes.
        /// </summary>
        internal static string TICKET_IS_CLOSED {
            get {
                return ResourceManager.GetString("TICKET_IS_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date always greater than or equal to from date..
        /// </summary>
        internal static string To_Date_Always_Greater_than_or_Equal_to_From_Date {
            get {
                return ResourceManager.GetString("To_Date_Always_Greater_than_or_Equal_to_From_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date always greater than or equal to from date..
        /// </summary>
        internal static string To_Date_Is_Always_Greater_Than_Or_Equal_To_From_Date {
            get {
                return ResourceManager.GetString("To_Date_Is_Always_Greater_Than_Or_Equal_To_From_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAN number already exists..
        /// </summary>
        internal static string UAN_Number_Already_Exists {
            get {
                return ResourceManager.GetString("UAN_Number_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot apply for leaves in the training period..
        /// </summary>
        internal static string Under_Training_Period {
            get {
                return ResourceManager.GetString("Under_Training_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled on is required!.
        /// </summary>
        internal static string Uninstalled_On_Is_Required {
            get {
                return ResourceManager.GetString("Uninstalled_On_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists, please try another one..
        /// </summary>
        internal static string User_Name_Already_Exist {
            get {
                return ResourceManager.GetString("User_Name_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week of already exist..
        /// </summary>
        internal static string Week_Already_Exist {
            get {
                return ResourceManager.GetString("Week_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week date is required..
        /// </summary>
        internal static string Week_Date {
            get {
                return ResourceManager.GetString("Week_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week date already exists..
        /// </summary>
        internal static string WEEK_DATE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("WEEK_DATE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This weekday already exists..
        /// </summary>
        internal static string WEEK_DAY_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("WEEK_DAY_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A weekday is required..
        /// </summary>
        internal static string Week_Day_Required {
            get {
                return ResourceManager.GetString("Week_Day_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A week in a year is required..
        /// </summary>
        internal static string Week_In_Year {
            get {
                return ResourceManager.GetString("Week_In_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A week number in a month required..
        /// </summary>
        internal static string Week_No_In_Month {
            get {
                return ResourceManager.GetString("Week_No_In_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFH has been approved..
        /// </summary>
        internal static string WFH_Already_Approved {
            get {
                return ResourceManager.GetString("WFH_Already_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFH has been approved for these dates..
        /// </summary>
        internal static string WFH_Already_Approved_Dates {
            get {
                return ResourceManager.GetString("WFH_Already_Approved_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFH has been rejected..
        /// </summary>
        internal static string WFH_Already_Rejected {
            get {
                return ResourceManager.GetString("WFH_Already_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You do not have the permission..
        /// </summary>
        internal static string You_DoNot_Have_Permission {
            get {
                return ResourceManager.GetString("You_DoNot_Have_Permission", resourceCulture);
            }
        }
    }
}
