//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranSmart.Domain.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhaar must be 12 numbers..
        /// </summary>
        internal static string Aadhaar_Must_Be_12_Numbers {
            get {
                return ResourceManager.GetString("Aadhaar_Must_Be_12_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be 18 to join..
        /// </summary>
        internal static string Age_must_be_18_to_join {
            get {
                return ResourceManager.GetString("Age_must_be_18_to_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both account numbers need to be same!.
        /// </summary>
        internal static string Both_Account_Numbers_Need_To_Be_Same {
            get {
                return ResourceManager.GetString("Both_Account_Numbers_Need_To_Be_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centum club must be greater than or equal to 0..
        /// </summary>
        internal static string Centum_Club_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Centum_Club_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of birth should be less than the current date..
        /// </summary>
        internal static string Date_of_birth_should_be_less_than_current_date {
            get {
                return ResourceManager.GetString("Date_of_birth_should_be_less_than_current_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of joining should be greater than the date of birth..
        /// </summary>
        internal static string Date_Of_Joining_Should_Be_Greater_Than_Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date_Of_Joining_Should_Be_Greater_Than_Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of joining should be less than the current date..
        /// </summary>
        internal static string Date_of_joining_should_be_less_than_current_date {
            get {
                return ResourceManager.GetString("Date_of_joining_should_be_less_than_current_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of last working day should be greater than the date of joining..
        /// </summary>
        internal static string Date_Of_Last_Working_Should_Be_Greater_Than_Date_Of_Joining {
            get {
                return ResourceManager.GetString("Date_Of_Last_Working_Should_Be_Greater_Than_Date_Of_Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double pay must be greater than or equal to 0..
        /// </summary>
        internal static string Double_Pay_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Double_Pay_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No is required..
        /// </summary>
        internal static string Employee_No_Is_Required {
            get {
                return ResourceManager.GetString("Employee_No_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External quality feedback must be greater than or equal to 0..
        /// </summary>
        internal static string External_Quality_Feedback_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("External_Quality_Feedback_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax files and arrears must be greater than or equal to 0..
        /// </summary>
        internal static string Fax_Files_And_Arrears_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Fax_Files_And_Arrears_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First minute incentives must be greater than or equal to 0..
        /// </summary>
        internal static string First_Minute_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("First_Minute_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal quality feedback must be greater than or equal to 0..
        /// </summary>
        internal static string Internal_Quality_Feedback_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Internal_Quality_Feedback_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last working date is required.
        /// </summary>
        internal static string Last_Working_Date_Is_Required {
            get {
                return ResourceManager.GetString("Last_Working_Date_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late coming deduction must be greater than or equal to 0..
        /// </summary>
        internal static string Late_Coming_Deduction_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Late_Coming_Deduction_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loan deduction date should be greater than or equal to the loan release date..
        /// </summary>
        internal static string Loan_deducation_date_should_be_greaterthan_or_equal_to_the_loan_release_date {
            get {
                return ResourceManager.GetString("Loan_deducation_date_should_be_greaterthan_or_equal_to_the_loan_release_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The marriage anniversary should be greater than the date of birth..
        /// </summary>
        internal static string Marriage_anniversary_should_be_greater_than_date_of_birth {
            get {
                return ResourceManager.GetString("Marriage_anniversary_should_be_greater_than_date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The monthly amount should be less than the loan amount..
        /// </summary>
        internal static string Monthly_amount_should_be_less_than_loan_Amount {
            get {
                return ResourceManager.GetString("Monthly_amount_should_be_less_than_loan_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night shift must be greater than or equal to 0..
        /// </summary>
        internal static string Night_Shift_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Night_Shift_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other deductions must be greater than or equal to 0..
        /// </summary>
        internal static string Other_Deduction_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Other_Deduction_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Other_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Other_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayMonth is required..
        /// </summary>
        internal static string PayMonth_Is_Required {
            get {
                return ResourceManager.GetString("PayMonth_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Production_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Production_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuality incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Punctuality_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Punctuality_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[2-9]{1}[0-9]{3}[ -]?[0-9]{4}[ -]?[0-9]{4}$.
        /// </summary>
        internal static string RegEx_Aadhar {
            get {
                return ResourceManager.GetString("RegEx_Aadhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?i)[A-Z]{3}[ABCFGHLJPTF]{1}[A-Z]{1}[0-9]{4}[A-Z]{1}$.
        /// </summary>
        internal static string RegEx_PAN {
            get {
                return ResourceManager.GetString("RegEx_PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Spot_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Spot_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Sunday_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Sunday_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition team incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Transition_Team_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Transition_Team_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized leave deduction must be greater than or equal to 0..
        /// </summary>
        internal static string Unauthorized_Leave_Deduction_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Unauthorized_Leave_Deduction_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly star incentives must be greater than or equal to 0..
        /// </summary>
        internal static string Weekly_Star_Incentives_Must_Be_Greater_Than_Or_Equal_To_0 {
            get {
                return ResourceManager.GetString("Weekly_Star_Incentives_Must_Be_Greater_Than_Or_Equal_To_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of passing should be less than the current date..
        /// </summary>
        internal static string Year_of_Passing_Should_be_Less_than_Current_Date {
            get {
                return ResourceManager.GetString("Year_of_Passing_Should_be_Less_than_Current_Date", resourceCulture);
            }
        }
    }
}
